version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5435:5432"
    volumes:
      - postgres_go_data:/var/lib/postgresql/data

volumes:
  postgres_go_data:
